// <auto-generated />
using System;
using API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(ToDoContext))]
    [Migration("20250224195723_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("API.Models.Tasks", b =>
                {
                    b.Property<int>("task_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("end_Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("end_Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("start_Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("start_Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("user_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("task_Id");

                    b.ToTable("ToDos");

                    b.HasData(
                        new
                        {
                            task_Id = 1,
                            title = "test1"
                        },
                        new
                        {
                            task_Id = 2,
                            title = "test2"
                        },
                        new
                        {
                            task_Id = 3,
                            title = "test3"
                        },
                        new
                        {
                            task_Id = 4,
                            title = "test4"
                        },
                        new
                        {
                            task_Id = 5,
                            title = "test5"
                        });
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Property<int>("user_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("user_Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            user_Id = 1,
                            name = "admin"
                        },
                        new
                        {
                            user_Id = 2,
                            name = "user"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
